name: Validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
        cache-dependency-path: |
          package-lock.json
          functions/package-lock.json

    - name: Install dashboard dependencies
      run: npm ci

    - name: Install functions dependencies
      run: npm --prefix functions ci

    - name: Validate
      run: npm test
